#ifndef CONSTANTS
#define CONSTANTS

#define MAIN_VIEW_WIDTH 480
#define MAIN_VIEW_HEIGHT 272

#define EXP_VIEW_WIDTH 68
#define EXP_VIEW_HEIGHT 52

#define ROLL_STEP 2

#define PLAYER_POS_X 100
#define PLAYER_POS_Y 95

#define ENEMY_POS_X  150
#define ENEMY_POS_Y  150

#define TILE_SIZE 32

// experimentally found
#define PLAYER_TILE_OFFSET_RIGHT 5
#define PLAYER_TILE_OFFSET_MIDDLE 5
#define PLAYER_TILE_OFFSET_LEFT 4

#define PLAYER_X_OFFSET_RIGHT (-8)
#define PLAYER_X_OFFSET_MIDDLE (-20)
#define PLAYER_X_OFFSET_LEFT (-10)

#define ENEMY_CYCLE_LIMIT 120

#define JUMP_LIMIT 25

#define NO_ENEMIES 2

enum TILE { VOID, CONCRETE_BLOCK, MINE_BLOCK, FINISH_BLOCK };

#endif